version: '3.2'
services:
  web:
    image: maxisme/taskermaritime.co.uk:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.taskermaritimecouk.rule=Host(`taskermaritime.co.uk`)"
        - "traefik.http.services.taskermaritimecouk.loadbalancer.server.port=8080"
        - "traefik.http.routers.taskermaritimecouk.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true